#    application_helper.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 23, 2013
#
# Description
#    Helper for the whole application
#
module ApplicationHelper
end
