#    light_power_helper.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 26, 2013
#
# Description
#    Helper for light power
#
module LightPowerHelper
end
