#    application_controller.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 23, 2013
#
# Description
#    Base class for controllers
#
class ApplicationController < ActionController::Base
  protect_from_forgery
end
