#    application_controller.rb
# Purpose: Mid term demo
# Author: generated by rails
# CSE 467S -- Embedded Computing Systems
# WUSTL, Spring 2013
# Date: Mar., 23, 2013
#
# Description
#    Base class for controllers
#
class ApplicationController < ActionController::Base
  protect_from_forgery

  def reset_system
  	RoughMovement.destroy_all
  	HeartRate.destroy_all
  	LightPower.destroy_all

  	redirect_to root_path
  end

end
